name: nb_conda_store_kernels
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - traitlets
  - jupyter_client
  - pip
  - pip:
    - 'conda-store@git+https://github.com/ClaytonAstrom/conda-store.git@4.12-AL3-401#egg=subdir&subdirectory=conda-store'
