name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  release-nb_conda_store_kernels:
    name: 'PyPi Release nb_conda_store_kernels'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install twine
        run: |
          pip install twine build
      - name: Build and Distribute
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build --sdist
          twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
